default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: bitlasoft
  host: localhost
  port: 5432


development:
  <<: *default
  database: invoice_ai_development

test:
  <<: *default
  database: invoice_ai_test

production:
  primary: &primary_production
    <<: *default
    database: invoice_ai_production
  cache:
    <<: *primary_production
    database: invoice_ai_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: invoice_ai_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: invoice_ai_production_cable
    migrations_paths: db/cable_migrate
